package com.pikit.shared.enums;

public enum StatType {
	TEAM_COMPARISON, TEAM_ACCUMULATION, CALCULATION, WEEKLY_UPDATED_TEAM_STAT, TEAM_STREAK, VALUE_COMPARISON, SPREAD_CALCULATION, GAME_WINNER_MONEY_LINE_CALCULATION, OPPOSITE_TEAM_STAT, SIMULTANEOUS_EVENT_STAT, STANDINGS_STAT, TEAM_METADATA_STAT
}
